### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by grayghostvisuals** [michaeltrilford/transformicons-simplified#1]
Would you mind removing this line from your README?

> I'm looking for a less CSS heavy option than what is available at transformicons.com

The reason being is it's an early stage project plus it's a bit unfair to say that since you never posted to the issue tracker with your concerns. I think this comment unfairly paints the project in a bad light.

**Comment by michaeltrilford** [comment]
Hello @grayghostvisuals,

Sorry mate, it wasn't my intention to paint the project in bad light. Just to clarify, I don't have any concerns with the project, I think it's fantastic. I just have a personal crusade to use CSS in the most lightweight way possible. This was my attempt.

Mike.

**Comment by grayghostvisuals** [comment]
It would be great to see a mix of both on the project and again it would have been nice to see you post your concerns on the issue tracker.
